name: GitHub Actions - Workflow Dispatch Template
run-name: Running - ${{ github.event_name }}
on: [workflow_dispatch]

jobs:
  t2-workflow-dispatch:
    runs-on: ubuntu-latest
    steps:
      - name: Comentario
        run: echo "Comentário WORKFLOW DISPATCH - Básico"
