name: GitHub Actions - Workflow Dispatch String Template
run-name: Running - ${{ github.event_name }}

on:
  workflow_dispatch:
    inputs:
      serie:
        description: 'Digite aqui sua série favorita'
        type: string

jobs:
  run-workflow-dispatch:
    runs-on: ubuntu-latest
    steps:
      - name: Comentario
        run: |
          echo "Comentário WORKFLOW DISPATCH string"
          echo "Minha série favorita: ${{ github.event.inputs.serie }}"
