name: GitHub Actions - Cron Job Template
run-name: Running - ${{ github.event_name }}
on:
  schedule:
    # 5h e 30min nas segundas e quartas-feiras
    - cron: '30 5 * * 1,3' 
    # 19h e 0min nas terças-feiras
    - cron: '0 19 * * 2' 
    # 23h e 59min do dia 31 de dezembro
    - cron: '59 23 31 12 *' 

jobs:
  teste-schedule:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Já este passo sempre será executado"
